-- BierKompas: bier-spijscombinaties ("Foodpairing Hub"), data aangeleverd door Huub.
-- Uitvoeren via het Supabase-dashboard: SQL Editor -> New query -> plak dit bestand -> Run.
--
-- Smaak_Drie_Woorden, Tripadvisor_Rating en Proeflokaal_Sfeer staan in het
-- bronbestand van Huub maar waren in alle 162 rijen leeg -- de kolommen
-- blijven wel bestaan zodat een beheerder ze later per combinatie kan
-- aanvullen via de admin-pagina, zonder dat er iets verzonnen wordt.

create table if not exists public.beer_pairings (
    id bigint generated always as identity primary key,
    brouwerij text not null,
    biernaam text not null,
    link_website text,
    aanbevolen_gerecht text not null,
    aankoop_context text,
    prijs text,
    smaak_drie_woorden text,
    tripadvisor_rating numeric,
    proeflokaal_sfeer text,
    created_at timestamptz not null default now()
);

alter table public.beer_pairings enable row level security;

drop policy if exists "Pairings: iedereen mag lezen" on public.beer_pairings;
create policy "Pairings: iedereen mag lezen" on public.beer_pairings
    for select using (true);

drop policy if exists "Pairings: alleen beheerders mogen wijzigen" on public.beer_pairings;
create policy "Pairings: alleen beheerders mogen wijzigen" on public.beer_pairings
    for all using (
        exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin)
    )
    with check (
        exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin)
    );

-- 162 combinaties uit "belgisch brouwerijen met spijs.xlsx" (aangeleverd door Huub).
insert into public.beer_pairings
    (brouwerij, biernaam, link_website, aanbevolen_gerecht, aankoop_context, prijs, smaak_drie_woorden, tripadvisor_rating, proeflokaal_sfeer)
values
    ('Brouwerij Hoop', 'Koperen Hoogte', 'https://www.hoopbier.nl', 'Gestoofde runderwang met kruidkoek', 'Webshop / Slijterij', '€ 2', null, null, null),
    ('Brouwerij Hoop', 'Bleeke Nelis', 'https://www.hoopbier.nl', 'Gegrilde dorade met citroen en venkel', 'Webshop / Supermarkt', '€ 2', null, null, null),
    ('Brouwerij Hoop', 'Waterwolf', 'https://www.hoopbier.nl', 'Blauwaderkaas en donkere chocolade', 'Webshop / Slijterij', '€ 3', null, null, null),
    ('Brouwerij Hoop', 'Oude Zaan', 'https://www.hoopbier.nl', 'Oude Zaanse kaas met mosterd', 'Webshop / Proeflokaal', '€ 2', null, null, null),
    ('Brouwerij Hoop', 'Schotse Hooglander', 'https://www.hoopbier.nl', 'Gegrilde lamsracks met rozemarijn', 'Webshop / Slijterij', '€ 3', null, null, null),
    ('De Naeckte Brouwers', 'Naeckte Nimf', 'https://www.naecktebrouwers.nl', 'Vegan burger met geitenkaas en vijg', 'Proeflokaal / Webshop', '€ 3', null, null, null),
    ('De Naeckte Brouwers', 'Naeckte Non', 'https://www.naecktebrouwers.nl', 'Geroosterd varkensbuikspek', 'Proeflokaal / Slijter', '€ 3', null, null, null),
    ('De Naeckte Brouwers', 'Naeckte Zonnegloed', 'https://www.naecktebrouwers.nl', 'Gebraden kip met citroenkruiden', 'Webshop / Slijterij', '€ 2', null, null, null),
    ('De Naeckte Brouwers', 'Naeckte Grand Cru', 'https://www.naecktebrouwers.nl', 'Rijpe boerenkaas met noten', 'Proeflokaal / Slijter', '€ 3', null, null, null),
    ('De Naeckte Brouwers', 'Naeckte Spits', 'https://www.naecktebrouwers.nl', 'Gestoofde mosselen met patat', 'Slijterij / Horeca', '€ 2', null, null, null),
    ('Wispe Brouwerij', 'Wispe Wit', 'https://www.wispe.nl', 'Gestoomde kabeljauw met citroen butter sauce', 'Webshop / Grand Café', '€ 2', null, null, null),
    ('Wispe Brouwerij', 'Wispe Blond', 'https://www.wispe.nl', 'Beef Teriyaki en pikante kip', 'Webshop / Grand Café', '€ 2', null, null, null),
    ('Wispe Brouwerij', 'Wispe IPA', 'https://www.wispe.nl', 'Black Angus burger met cheddar en bacon', 'Webshop / Grand Café', '€ 3', null, null, null),
    ('Wispe Brouwerij', 'Wispe Tripel', 'https://www.wispe.nl', 'Gegrilde lamskotelet met tijm', 'Webshop / Grand Café', '€ 3', null, null, null),
    ('Wispe Brouwerij', 'Wispe Quadrupel', 'https://www.wispe.nl', 'Biefstuk met champignons en boerenkaas', 'Webshop / Grand Café', '€ 3', null, null, null),
    ('Wispe Brouwerij', 'Wispe Porter', 'https://www.wispe.nl', 'Puur chocoladedessert of warme brownie', 'Webshop / Grand Café', '€ 3', null, null, null),
    ('Rock City Brewing', 'Shaky Bones DDH IPA', 'https://rockcitybrewing.nl', 'Low & slow smoked pulled pork', 'Webshop / Brewpub', '€ 3', null, null, null),
    ('Rock City Brewing', 'Koene Ridder Tripel', 'https://rockcitybrewing.nl', 'Gegrilde spareribs met barbecuesaus', 'Webshop / Brewpub', '€ 2', null, null, null),
    ('Rock City Brewing', 'Buried Treasure Double Stout', 'https://rockcitybrewing.nl', 'Smoked brisket en blauwe schimmelkaas', 'Webshop / Brewpub', '€ 4', null, null, null),
    ('Rock City Brewing', 'Tropical White', 'https://rockcitybrewing.nl', 'Mexicaanse taco''s met limoen en vis', 'Webshop / Brewpub', '€ 3', null, null, null),
    ('Rock City Brewing', 'Twisted Blond', 'https://rockcitybrewing.nl', 'Gegrilde kipsaté met pinda-kokossaus', 'Webshop / Brewpub', '€ 3', null, null, null),
    ('Jopen', 'Mooi Nel IPA', 'https://www.jopenkerk.nl', 'Indiaase curry of pittige kip', 'Supermarkt / Jopenkerk', '€ 2', null, null, null),
    ('Jopen', 'Koyt', 'https://www.jopenkerk.nl', 'Gestoofd wild met stoofperen', 'Webshop / Jopenkerk', '€ 3', null, null, null),
    ('Jopen', 'Hoppenbier', 'https://www.jopenkerk.nl', 'Jonge geitenkaas op geroosterd brood', 'Supermarkt / Webshop', '€ 2', null, null, null),
    ('Jopen', 'Lentebier', 'https://www.jopenkerk.nl', 'Asperges op traditionele wijze', 'Supermarkt / Webshop', '€ 2', null, null, null),
    ('Jopen', 'Jacobus RP Pale Ale', 'https://www.jopenkerk.nl', 'Gegrilde hamburgers en cheddarkaas', 'Webshop / Jopenkerk', '€ 2', null, null, null),
    ('Jopen', 'Ongelovige Thomas', 'https://www.jopenkerk.nl', 'Oude boerenkaas of zware wildstoof', 'Webshop / Slijterij', '€ 3', null, null, null),
    ('Hertog Jan', 'Grand Prestige', 'https://www.hertogjan.nl', 'Rijpe rijpingskaas of pure chocolademousse', 'Supermarkt / Slijter', '€ 3', null, null, null),
    ('Hertog Jan', 'Bockbier', 'https://www.hertogjan.nl', 'Klassiek draadjesvlees met rode kool', 'Supermarkt / Horeca', '€ 2', null, null, null),
    ('Hertog Jan', 'Tripel', 'https://www.hertogjan.nl', 'Spaanse paella met gamba''s en kip', 'Supermarkt / Slijter', '€ 2', null, null, null),
    ('Hertog Jan', 'Karakter', 'https://www.hertogjan.nl', 'Gegrilde varkenshaas met champignonsaus', 'Supermarkt / Slijter', '€ 2', null, null, null),
    ('Brouwerij ''t IJ', 'Zatte Tripel', 'https://www.brouwerijij.nl', 'Oude Amsterdamse kaas en bitterballen', 'Supermarkt / Proeflokaal', '€ 2', null, null, null),
    ('Brouwerij ''t IJ', 'Natte Dubbel', 'https://www.brouwerijij.nl', 'Lamskoteletten of geroosterde groenten', 'Supermarkt / Proeflokaal', '€ 2', null, null, null),
    ('Brouwerij ''t IJ', 'IJwit', 'https://www.brouwerijij.nl', 'Thaise vissalade met koriander en limoen', 'Supermarkt / Proeflokaal', '€ 2', null, null, null),
    ('Brouwerij ''t IJ', 'IIPA', 'https://www.brouwerijij.nl', 'Pikante nacho''s met jalapeños', 'Webshop / Slijterij', '€ 3', null, null, null),
    ('Brouwerij ''t IJ', 'Vrij (0.5%)', 'https://www.brouwerijij.nl', 'Verse tonijnsalade of lichte pasta', 'Supermarkt / Proeflokaal', '€ 2', null, null, null),
    ('Stadsbrouwerij De Drie Ringen', 'Amersfoorts Blond', 'https://www.drie-ringen.nl', 'Klassiek plankje Hollandse kazen', 'Slijter / Proeflokaal', '€ 2', null, null, null),
    ('Stadsbrouwerij De Drie Ringen', 'Vuursteentje', 'https://www.drie-ringen.nl', 'Gegrild rood vlees met peperjus', 'Slijter / Proeflokaal', '€ 3', null, null, null),
    ('Stadsbrouwerij De Drie Ringen', 'Stadsbock', 'https://www.drie-ringen.nl', 'Herfststamppot met rookworst', 'Slijter / Proeflokaal', '€ 3', null, null, null),
    ('Uiltje Brewing Company', 'Bird of Prey IPA', 'https://www.uiltjebrewing.com', 'Pikante Indiaase vindaloo of taco''s', 'Supermarkt / Webshop', '€ 2', null, null, null),
    ('Uiltje Brewing Company', 'Trackdown Pale Ale', 'https://www.uiltjebrewing.com', 'Gegrilde kipsalade of gegrilde vis', 'Supermarkt / Webshop', '€ 2', null, null, null),
    ('Uiltje Brewing Company', 'Dr. Raptor Imperial IPA', 'https://www.uiltjebrewing.com', 'Rijke blauwschimmelkaas of gegrilde ribeye', 'Webshop / Slijterij', '€ 3', null, null, null),
    ('Uiltje Brewing Company', 'Prima Donna', 'https://www.uiltjebrewing.com', 'Citroen meringue taart of verse aardbeien', 'Webshop / Slijterij', '€ 3', null, null, null),
    ('Texelse Bierbrouwerij', 'Skuumkoppe', 'https://www.texels.nl', 'Texels lamsvlees of romige oude kaas', 'Supermarkt / Horeca', '€ 2', null, null, null),
    ('Texelse Bierbrouwerij', 'Texels Tuunwal Tripel', 'https://www.texels.nl', 'Gegrilde varkenshaas met honing-mosterd', 'Supermarkt / Webshop', '€ 2', null, null, null),
    ('Texelse Bierbrouwerij', 'Texels Overzee IPA', 'https://www.texels.nl', 'Garnalencroquetten of gebakken schol', 'Supermarkt / Webshop', '€ 2', null, null, null),
    ('Texelse Bierbrouwerij', 'Texels Stormbock', 'https://www.texels.nl', 'Rijke hazengoulash met rode kool', 'Supermarkt / Slijter', '€ 2', null, null, null),
    ('vandeStreek bier', 'Playground IPA (0.5%)', 'https://www.vandestreekbier.nl', 'Lichte gegrilde groenten en geitenkaas', 'Supermarkt / Webshop', '€ 2', null, null, null),
    ('vandeStreek bier', 'Hazy Weekend', 'https://www.vandestreekbier.nl', 'Mexicaanse nacho''s met guacamole', 'Supermarkt / Webshop', '€ 3', null, null, null),
    ('vandeStreek bier', 'Turf & Jenever', 'https://www.vandestreekbier.nl', 'Gerookte zalm en rijke eend', 'Webshop / Slijterij', '€ 4', null, null, null),
    ('vandeStreek bier', 'Broeders Blond', 'https://www.vandestreekbier.nl', 'Gegrilde kipsaté met satésaus', 'Supermarkt / Webshop', '€ 2', null, null, null),
    ('Brouwerij Kompaan', 'Bondgenoot Pale Ale', 'https://www.kompaanbier.nl', 'Fish and chips met remouladesaus', 'Webshop / Craft Bar', '€ 2', null, null, null),
    ('Brouwerij Kompaan', 'Bloedbroeder', 'https://www.kompaanbier.nl', 'Blackened steak met pepersaus', 'Webshop / Craft Bar', '€ 3', null, null, null),
    ('Brouwerij Kompaan', 'Handlanger Double IPA', 'https://www.kompaanbier.nl', 'Pikante chorizo of gerookte ribs', 'Webshop / Craft Bar', '€ 3', null, null, null),
    ('Brouwerij Kompaan', 'Levensgenieter', 'https://www.kompaanbier.nl', 'Verse caesar salade met kip', 'Webshop / Craft Bar', '€ 2', null, null, null),
    ('Brouwerij De Hemel', 'Nieuw Liefde', 'https://www.brouwerijdeemmer.nl', 'Lichte zomersalades en jonge kaas', 'Proeflokaal / Slijterij', '€ 2', null, null, null),
    ('Brouwerij De Hemel', 'Helse Engel', 'https://www.brouwerijdeemmer.nl', 'Gegrilde ribeye met kruidenboter', 'Proeflokaal / Slijterij', '€ 3', null, null, null),
    ('Brouwerij De Hemel', 'Serafijn', 'https://www.brouwerijdeemmer.nl', 'Wildzwijnstoofschotel met cranberry', 'Proeflokaal / Slijterij', '€ 3', null, null, null),
    ('Maximus Brouwerij', 'Pandora Pale Ale', 'https://www.maximusbrouwerij.nl', 'Gegrilde kip en milde curry''s', 'Supermarkt / Webshop', '€ 2', null, null, null),
    ('Maximus Brouwerij', 'Brutus', 'https://www.maximusbrouwerij.nl', 'Smoked brisket en gerookte amandelen', 'Supermarkt / Webshop', '€ 2', null, null, null),
    ('Maximus Brouwerij', 'Little Session IPA', 'https://www.maximusbrouwerij.nl', 'Lichte garnalencocktail', 'Webshop / Slijterij', '€ 2', null, null, null),
    ('Kaapse Brouwerij', 'Kaapse Karel', 'https://www.kaapsebrouwers.nl', 'Pikante streetfood en Koreaanse fried chicken', 'Webshop / Fenix Food', '€ 3', null, null, null),
    ('Kaapse Brouwerij', 'Kaapse Harrie', 'https://www.kaapsebrouwers.nl', 'Verse oesters of ceviche', 'Webshop / Fenix Food', '€ 3', null, null, null),
    ('Kaapse Brouwerij', 'Kaapse Carrie', 'https://www.kaapsebrouwers.nl', 'Affogato dessert of tiramisu', 'Webshop / Slijterij', '€ 4', null, null, null),
    ('Oproer Brouwerij', '24/7 Session IPA', 'https://www.Oproer.nl', 'Vegan shoarma met knoflooksaus', 'Webshop / Restobar', '€ 2', null, null, null),
    ('Oproer Brouwerij', 'Imperial Stout', 'https://www.Oproer.nl', 'Vegan chocoladetaart met framboos', 'Webshop / Restobar', '€ 4', null, null, null),
    ('Oproer Brouwerij', 'Cosmic IPA', 'https://www.Oproer.nl', 'Pikante curry''s met kokosmelk', 'Webshop / Restobar', '€ 3', null, null, null),
    ('Frontaal Brewing Co.', 'Juice Punch', 'https://www.frontaalbrewingcompany.com', 'Gegrilde zalm met mango salsa', 'Webshop / Craft Bar', '€ 3', null, null, null),
    ('Frontaal Brewing Co.', 'Bulldog', 'https://www.frontaalbrewingcompany.com', 'Rijke stoofschotel met ontbijtkoek', 'Webshop / Craft Bar', '€ 3', null, null, null),
    ('Frontaal Brewing Co.', 'Deer Hunter', 'https://www.frontaalbrewingcompany.com', 'Puur chocolade soufflé', 'Webshop / Craft Bar', '€ 5', null, null, null),
    ('Frontaal Brewing Co.', 'Andreas', 'https://www.frontaalbrewingcompany.com', 'Rijpe camembert met toast', 'Webshop / Craft Bar', '€ 3', null, null, null),
    ('Brouwerij Kees', 'Export Porter 1750', 'https://www.brouwerijkees.nl', 'Blauwe schimmelkaas (Stilton)', 'Webshop / Slijterij', '€ 3', null, null, null),
    ('Brouwerij Kees', 'Haze & Kicks', 'https://www.brouwerijkees.nl', 'Crispy calamari met citroenmayonaise', 'Webshop / Slijterij', '€ 3', null, null, null),
    ('Brouwerij Kees', 'Caramel Fudge Stout', 'https://www.brouwerijkees.nl', 'Vanille-ijs met karamelsaus', 'Webshop / Slijterij', '€ 4', null, null, null),
    ('De Halve Maan (NL distribution)', 'Straffe Hendrik Tripel', 'https://www.brouwerijdehalvemaan.nl', 'Rijke vissoep met rouille', 'Supermarkt / Slijter', '€ 2', null, null, null),
    ('De Halve Maan (NL distribution)', 'Brugse Zot Blond', 'https://www.brouwerijdehalvemaan.nl', 'Gegrilde kalfskotelet', 'Supermarkt / Horeca', '€ 2', null, null, null),
    ('Brouwerij De Molen', 'Hel & Verdoemenis', 'https://www.geitenbrei.nl', 'Rijke vacherin mont d''or of pure chocola', 'Webshop / Proeflokaal', '€ 4', null, null, null),
    ('Brouwerij De Molen', 'Bommen & Granaten', 'https://www.geitenbrei.nl', 'Rijpe blauwe kaas of gedroogde vijgen', 'Webshop / Proeflokaal', '€ 4', null, null, null),
    ('Brouwerij De Molen', 'Op & Top', 'https://www.geitenbrei.nl', 'Lichte barbecue gerechten en burgers', 'Supermarkt / Webshop', '€ 2', null, null, null),
    ('Brouwerij De Molen', 'Dag & Nacht', 'https://www.geitenbrei.nl', 'Oude brokkelkaas en walnoten', 'Webshop / Slijterij', '€ 3', null, null, null),
    ('Brouwerij ''t IJ x Duvel', 'IJbok', 'https://www.brouwerijduvelmoortgat.nl', 'Gestoofde hertenbiefstuk met rode kool', 'Supermarkt / Proeflokaal', '€ 2', null, null, null),
    ('Uiltje Brewing Company', 'Sequence Series Stout', 'https://www.brouwerijhetuiltje.nl', 'Tiramisu of chocolade mousse', 'Webshop / Craft Bar', '€ 5', null, null, null),
    ('Brouwerij Leeuw', 'Valkenburgs Wit', 'https://www.brouwerijdeleeuw.nl', 'Lichte zomersalades met geitenkaas', 'Slijterij / Horeca', '€ 2', null, null, null),
    ('Grolsch Proefbrouwerij', 'Karakter', 'https://www.grolsch.nl', 'Stoofvlees met friet', 'Supermarkt / Horeca', '€ 1', null, null, null),
    ('Grolsch Proefbrouwerij', 'Weizen', 'https://www.grolsch.nl', 'Garnalen en verse vissalades', 'Supermarkt / Horeca', '€ 2', null, null, null),
    ('Sint Christoffel', 'Christoffel Bier', 'https://www.brouwerijstchristoffel.nl', 'Duitse bratwurst met zuurkool', 'Slijterij / Webshop', '€ 2', null, null, null),
    ('Sint Christoffel', 'Christoffel Robertus', 'https://www.brouwerijstchristoffel.nl', 'Gegrild kalfsvlees met jus', 'Slijterij / Webshop', '€ 2', null, null, null),
    ('Brand Bierbrouwerij', 'Brand Imperator', 'https://www.brand.nl', 'Gestoofde konijnenbout met pruimen', 'Supermarkt / Horeca', '€ 2', null, null, null),
    ('Brand Bierbrouwerij', 'Brand IPA', 'https://www.brand.nl', 'Aziatische roerbak met chili', 'Supermarkt / Horeca', '€ 2', null, null, null),
    ('Brand Bierbrouwerij', 'Brand Dubbelbock', 'https://www.brand.nl', 'Klassieke hachee met aardappelpuree', 'Supermarkt / Horeca', '€ 2', null, null, null),
    ('Lindeboom Brouwerij', 'Gouverneur Blond', 'https://www.brouwerijlindeboom.nl', 'Gegrilde tonijnsteak', 'Slijterij / Supermarkt', '€ 2', null, null, null),
    ('Lindeboom Brouwerij', 'Gouverneur Dubbel', 'https://www.brouwerijlindeboom.nl', 'Lamsrack met tijmjus', 'Slijterij / Supermarkt', '€ 2', null, null, null),
    ('Lindeboom Brouwerij', 'Gouverneur Stout', 'https://www.brouwerijlindeboom.nl', 'Oude Limburgse grottenkaas', 'Slijterij / Supermarkt', '€ 2', null, null, null),
    ('Gulpener Bierbrouwerij', 'Oer-Pilsner', 'https://www.brouwerijgulpener.nl', 'Verse oesters of gebakken mosselen', 'Supermarkt / Horeca', '€ 1', null, null, null),
    ('Gulpener Bierbrouwerij', 'Château Neercanne', 'https://www.brouwerijgulpener.nl', 'Gastronomisch kalfsvlees met truffel', 'Webshop / Horeca', '€ 6', null, null, null),
    ('Gulpener Bierbrouwerij', 'IJsbock', 'https://www.brouwerijgulpener.nl', 'Rijke appeltaart met vanille-ijs', 'Supermarkt / Webshop', '€ 3', null, null, null),
    ('Gulpener Bierbrouwerij', 'Limburgs Land Pils', 'https://www.brouwerijgulpener.nl', 'Frise salade met geitenkaas', 'Supermarkt / Horeca', '€ 1', null, null, null),
    ('Gulpener Bierbrouwerij', 'Gerardus Dubbel', 'https://www.brouwerijgulpener.nl', 'Klassieke Limburgse zuurvlees', 'Supermarkt / Horeca', '€ 2', null, null, null),
    ('Brouwerij Eem', 'Eem Bitter', 'https://www.brouwerijceven.nl', 'Klassieke Engelse cheddar cheese', 'Webshop / Slijterij', '€ 2', null, null, null),
    ('Brouwerij Eem', 'Eem Stout', 'https://www.brouwerijceven.nl', 'Oesters of roodschimmelkaas', 'Webshop / Slijterij', '€ 3', null, null, null),
    ('La Trappe Trappist', 'La Trappe Blond', 'https://www.brouwerijdekoningshoeven.nl', 'Gegrilde kip en milde visgerechten', 'Supermarkt / Proeflokaal', '€ 2', null, null, null),
    ('La Trappe Trappist', 'La Trappe Dubbel', 'https://www.brouwerijdekoningshoeven.nl', 'Gestoofde kalfswang met gegrilde groenten', 'Supermarkt / Proeflokaal', '€ 2', null, null, null),
    ('La Trappe Trappist', 'La Trappe Tripel', 'https://www.brouwerijdekoningshoeven.nl', 'Pikante Aziatische gerechten of eend', 'Supermarkt / Proeflokaal', '€ 2', null, null, null),
    ('La Trappe Trappist', 'La Trappe Quadrupel', 'https://www.brouwerijdekoningshoeven.nl', 'Blauwe schimmelkaas of dadelcake', 'Supermarkt / Proeflokaal', '€ 2', null, null, null),
    ('La Trappe Trappist', 'La Trappe ISID''OR', 'https://www.brouwerijdekoningshoeven.nl', 'Gegrilde varkenshaas met champignons', 'Supermarkt / Proeflokaal', '€ 2', null, null, null),
    ('La Trappe Trappist', 'La Trappe White Trappist', 'https://www.brouwerijdekoningshoeven.nl', 'Lichte vissalades met citroendressing', 'Supermarkt / Proeflokaal', '€ 2', null, null, null),
    ('Trappistenbrouwerij De Kievit', 'Zundert 8', 'https://www.zunderttrappist.nl', 'Geroosterd wildschijn of gegrilde steak', 'Slijterij / Webshop', '€ 2', null, null, null),
    ('Trappistenbrouwerij De Kievit', 'Zundert 10', 'https://www.zunderttrappist.nl', 'Oude trappistenkaas of stoofschotel', 'Slijterij / Webshop', '€ 3', null, null, null),
    ('Het Anker (NL Horeca)', 'Gouden Carolus Classic', 'https://www.brouwerijhetanker.be', 'Gestoofde runderkonijn met pruimen', 'Slijterij / Horeca', '€ 2', null, null, null),
    ('Het Anker (NL Horeca)', 'Gouden Carolus Tripel', 'https://www.brouwerijhetanker.be', 'Garnalencroquetten of gegrilde kabeljauw', 'Slijterij / Horeca', '€ 2', null, null, null),
    ('Oirschots Bier', 'Oirschots Blond', 'https://www.brouwerijvandeoirschotse.nl', 'Boerenkaasplankje van lokale boerderij', 'Slijterij / Horeca', '€ 2', null, null, null),
    ('Oirschots Bier', 'Oirschots Dubbel', 'https://www.brouwerijvandeoirschotse.nl', 'Gegrilde speklappen met appelmoes', 'Slijterij / Horeca', '€ 2', null, null, null),
    ('St. Bernardus (NL distribution)', 'Abt 12', 'https://www.brouwerijstbernardus.be', 'Rijpe stilton en pure chocolade', 'Supermarkt / Slijter', '€ 2', null, null, null),
    ('St. Bernardus (NL distribution)', 'Prior 8', 'https://www.brouwerijstbernardus.be', 'Stoofvlees met frites en mayonaise', 'Supermarkt / Slijter', '€ 2', null, null, null),
    ('St. Bernardus (NL distribution)', 'Tripel', 'https://www.brouwerijstbernardus.be', 'Gegrild kalfsvlees met citroen', 'Supermarkt / Slijter', '€ 2', null, null, null),
    ('St. Bernardus (NL distribution)', 'Wit', 'https://www.brouwerijstbernardus.be', 'Thaise salades en gewokte garnalen', 'Supermarkt / Slijter', '€ 2', null, null, null),
    ('Oirschotse Brouwerij', 'Zomerblond', 'https://www.vandeoirschotse.nl', 'Lichte kipsalade met verse ananas', 'Slijterij / Lokaal', '€ 2', null, null, null),
    ('Brouwerij Hoop', 'Czaar Peter', 'https://www.brouwerijhoop.nl', 'Rijke choco-lava cake met bosvruchten', 'Webshop / Proeflokaal', '€ 3', null, null, null),
    ('Brouwerij Hoop', 'Oudt Zaan', 'https://www.brouwerijhoop.nl', 'Hollandse stamppot rauwe andijvie', 'Webshop / Proeflokaal', '€ 2', null, null, null),
    ('Wispe Brouwerij', 'Wispe Session IPA', 'https://www.wispe.nl', 'Mexicaanse nacho''s met guacamole', 'Webshop / Grand Café', '€ 2', null, null, null),
    ('De Naeckte Brouwers', 'Naeckte Elegast', 'https://www.naecktebrouwers.nl', 'Rijk wild zwijn rollade', 'Proeflokaal / Slijter', '€ 3', null, null, null),
    ('Rock City Brewing', 'Second Date DIPA', 'https://rockcitybrewing.nl', 'Pikante buffalo chicken wings', 'Webshop / Brewpub', '€ 3', null, null, null),
    ('Jopen', 'Heavy Cross', 'https://www.jopenkerk.nl', 'Blauwe schimmelkaas met vijgenbrood', 'Webshop / Jopenkerk', '€ 4', null, null, null),
    ('Brouwerij ''t IJ', 'Biri', 'https://www.brouwerijij.nl', 'Verse taco''s met lime en koriander', 'Supermarkt / Proeflokaal', '€ 2', null, null, null),
    ('Uiltje Brewing Company', 'Pineapple Weizen', 'https://www.uiltjebrewing.com', 'Pikante Surinaamse roti', 'Webshop / Slijterij', '€ 3', null, null, null),
    ('vandeStreek bier', 'Grave Digger', 'https://www.vandestreekbier.nl', 'Rijke fudge brownie met noten', 'Webshop / Slijterij', '€ 4', null, null, null),
    ('Brouwerij Kompaan', 'Badgast', 'https://www.kompaanbier.nl', 'Gegrilde witvis met citroen', 'Webshop / Craft Bar', '€ 2', null, null, null),
    ('Maximus Brouwerij', 'Dakota', 'https://www.maximusbrouwerij.nl', 'Gegrilde lamskoteletten', 'Webshop / Slijterij', '€ 3', null, null, null),
    ('Frontaal Brewing Co.', 'Churchill', 'https://www.frontaalbrewingcompany.com', 'Boerenkaas met piccalilly', 'Webshop / Craft Bar', '€ 3', null, null, null),
    ('Brouwerij Kees', 'Peated Imperial Stout', 'https://www.brouwerijkees.nl', 'Gerookte zalm en droge worst', 'Webshop / Slijterij', '€ 4', null, null, null),
    ('Brouwerij De Molen', 'Vuur & Vlam', 'https://www.geitenbrei.nl', 'Indiase kip tikka masala', 'Webshop / Proeflokaal', '€ 3', null, null, null),
    ('Texelse Bierbrouwerij', 'Vrijbuiter', 'https://www.texels.nl', 'Geroosterde amandelen en oude kaas', 'Supermarkt / Webshop', '€ 2', null, null, null),
    ('La Trappe Trappist', 'La Trappe Nillis (0.0%)', 'https://www.brouwerijdekoningshoeven.nl', 'Verse caesar salade', 'Supermarkt / Proeflokaal', '€ 2', null, null, null),
    ('Trappistenbrouwerij De Kievit', 'Zundert 4', 'https://www.zunderttrappist.nl', 'Lichte quiche met prei en geitenkaas', 'Slijterij / Webshop', '€ 2', null, null, null),
    ('Kaapse Brouwerij', 'Kaapse Nelis', 'https://www.kaapsebrouwers.nl', 'Klassieke Engelse fish and chips', 'Webshop / Fenix Food', '€ 2', null, null, null),
    ('Oproer Brouwerij', 'Subculture', 'https://www.Oproer.nl', 'Vegan mushroom risotto', 'Webshop / Restobar', '€ 3', null, null, null),
    ('Stadsbrouwerij De Drie Ringen', 'Klassieker Blond', 'https://www.drie-ringen.nl', 'Kabeljauw uit de oven', 'Slijter / Proeflokaal', '€ 2', null, null, null),
    ('Brouwerij De Hemel', 'Lazarus', 'https://www.brouwerijdeemmer.nl', 'Panna cotta met rode vruchten', 'Proeflokaal / Slijterij', '€ 3', null, null, null),
    ('Gulpener Bierbrouwerij', 'Ur-Weizen', 'https://www.brouwerijgulpener.nl', 'Beierse pretzel met spundekäs', 'Supermarkt / Horeca', '€ 2', null, null, null),
    ('Brand Bierbrouwerij', 'Brand Weizen', 'https://www.brand.nl', 'Gebakken sliptong met citroen', 'Supermarkt / Horeca', '€ 2', null, null, null),
    ('Lindeboom Brouwerij', 'Kersenbier', 'https://www.brouwerijlindeboom.nl', 'Kersentaart of chocolademousse', 'Slijterij / Supermarkt', '€ 2', null, null, null),
    ('Brouwerij Hoop', 'Volendamer DBL', 'https://www.brouwerijhoop.nl', 'Gestoofde paling in groen', 'Webshop / Proeflokaal', '€ 3', null, null, null),
    ('Wispe Brouwerij', 'Wispe Weizen', 'https://www.wispe.nl', 'Bratwurst met zuurkool en mosterd', 'Webshop / Grand Café', '€ 2', null, null, null),
    ('De Naeckte Brouwers', 'Naeckte Koez', 'https://www.naecktebrouwers.nl', 'Duitse schnitzel met citroen', 'Proeflokaal / Slijter', '€ 2', null, null, null),
    ('Rock City Brewing', 'Buried Treasure Vanilla', 'https://rockcitybrewing.nl', 'Affogato vanille-ijs met espresso', 'Webshop / Brewpub', '€ 4', null, null, null),
    ('Jopen', 'Sin & Remorse', 'https://www.jopenkerk.nl', 'Rijke vacherin mont d''or', 'Webshop / Jopenkerk', '€ 4', null, null, null),
    ('Brouwerij ''t IJ', 'Columbus', 'https://www.brouwerijij.nl', 'Gegrild lamsvlees met knoflook', 'Supermarkt / Proeflokaal', '€ 2', null, null, null),
    ('Uiltje Brewing Company', 'SFC Session IPA', 'https://www.uiltjebrewing.com', 'Klassieke vette Smashburger', 'Supermarkt / Webshop', '€ 2', null, null, null),
    ('vandeStreek bier', 'Hop Art', 'https://www.vandestreekbier.nl', 'Pikante chorizo pizza', 'Webshop / Slijterij', '€ 3', null, null, null),
    ('Brouwerij Kompaan', 'Wout Imperial Stout', 'https://www.kompaanbier.nl', 'Puur chocolade truffels', 'Webshop / Craft Bar', '€ 4', null, null, null),
    ('Maximus Brouwerij', 'Sura', 'https://www.maximusbrouwerij.nl', 'Klassieke Thaise groene curry', 'Webshop / Slijterij', '€ 3', null, null, null),
    ('Frontaal Brewing Co.', 'Rhodesian', 'https://www.frontaalbrewingcompany.com', 'Gestoofde kalfswang met vijgen', 'Webshop / Craft Bar', '€ 4', null, null, null),
    ('Brouwerij Kees', 'Session IPA', 'https://www.brouwerijkees.nl', 'Verse caesar salade met garnalen', 'Webshop / Slijterij', '€ 2', null, null, null),
    ('Brouwerij De Molen', 'Mooi & Meedogenloos', 'https://www.geitenbrei.nl', 'Rijke boerenkaas met vijgencompote', 'Webshop / Proeflokaal', '€ 4', null, null, null),
    ('Texelse Bierbrouwerij', 'Springtij', 'https://www.texels.nl', 'Verse asperges met eiersalade', 'Supermarkt / Webshop', '€ 2', null, null, null),
    ('Kaapse Brouwerij', 'Kaapse Bea', 'https://www.kaapsebrouwers.nl', 'Zware runderstoofschotel', 'Webshop / Fenix Food', '€ 3', null, null, null),
    ('La Trappe Trappist', 'La Trappe Bockbier', 'https://www.brouwerijdekoningshoeven.nl', 'Wildzwijn biefstuk met vossenbessen', 'Supermarkt / Proeflokaal', '€ 2', null, null, null),
    ('Gulpener Bierbrouwerij', 'Sterk Rogge Tripel', 'https://www.gulpener.nl', 'Gegrild buikspek met ketjap', 'Supermarkt / Horeca', '€ 2', null, null, null),
    ('Hertog Jan', 'Enkel', 'https://www.hertogjan.nl', 'Lichte kipgerechten of gegrilde courgette', 'Supermarkt / Slijter', '€ 2', null, null, null),
    ('Brouwerij Hoop', 'Gooische Stout', 'https://www.brouwerijhoop.nl', 'Oesters met citroen en sjalot', 'Webshop / Proeflokaal', '€ 3', null, null, null),
    ('Wispe Brouwerij', 'Wispe Blonde Bock', 'https://www.wispe.nl', 'Gegrilde eendenborst met sinaasappelsaus', 'Webshop / Grand Café', '€ 2', null, null, null),
    ('Rock City Brewing', 'Hazy Pale Ale', 'https://rockcitybrewing.nl', 'Fish taco''s met koolsla', 'Webshop / Brewpub', '€ 2', null, null, null);

NOTIFY pgrst, 'reload schema';
