-- BierKompas: beheerders kunnen nu volledig nieuwe bieren aanmaken via de
-- admin-pagina, niet meer alleen barcodes bewerken van de 14 bieren die al
-- in de app-code stonden.
-- Uitvoeren via het Supabase-dashboard: SQL Editor -> New query -> plak dit bestand -> Run.
-- Vereist add_bieren_tabel.sql (eerder uitgevoerd).

-- Volledige bierinhoud, zodat een door een beheerder aangemaakt bier er in
-- de app precies zo uitziet als de 14 bestaande (naam, stijl, brouwerij en
-- barcode stonden al in de tabel).
alter table public.bieren add column if not exists abv text;
alter table public.bieren add column if not exists beschrijving text;
alter table public.bieren add column if not exists hoe_gemaakt text;
alter table public.bieren add column if not exists stijl_info text;
alter table public.bieren add column if not exists foto_url text;

-- De 14 bestaande bieren hebben een handmatig, vast id (1 t/m 14). Nieuwe
-- bieren die een beheerder toevoegt krijgen voortaan automatisch een id
-- vanaf 1000, zodat er nooit een botsing kan ontstaan met die vaste 14.
alter table public.bieren alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('public.bieren', 'id'), 1000, false);

NOTIFY pgrst, 'reload schema';
