/// Waarde van `item_type` in de Supabase-tabel `favorites`.
const breweryItemType = 'brewery';

class Brewery {
  final int id;
  final String title;
  final String distance;
  final String rating;
  final List<String> tags;
  final String location;
  final String? founded;
  final String about;
  final List<String> facts;
  final double latitude;
  final double longitude;

  const Brewery({
    required this.id,
    required this.title,
    required this.distance,
    required this.rating,
    required this.tags,
    required this.location,
    required this.about,
    required this.facts,
    required this.latitude,
    required this.longitude,
    this.founded,
  });
}

/// Partner op de Ontdek-pagina.
const grutePierProeflokaal = Brewery(
  id: 4,
  title: 'Grutte Pier Proeflokaal',
  distance: '2.4 km bij jou vandaan',
  rating: '4.8',
  tags: ['BIER & SPIJS', 'PARTNER'],
  location: 'Leeuwarden',
  about:
      'Een Friese brouwerij met proeflokaal, waar bier en eten samenkomen.',
  facts: [
    'Genoemd naar Grutte Pier, een Friese volksheld uit de 16e eeuw.',
    'Bier & spijs: probeer het Dubbel stoofvlees.',
  ],
  latitude: 53.2012,
  longitude: 5.7999,
);

/// Lokale brouwerijen die altijd beschikbaar blijven
/// als de online kaart tijdelijk niet werkt.
const breweries = [
  Brewery(
    id: 1,
    title: 'Brouwerij Hoop',
    distance: '0.8 km bij jou vandaan',
    rating: '4.8',
    tags: ['IPA', 'PROEFLOKAAL'],
    location: 'Zaandijk',
    about:
        'Een brouwerij met eigen proeflokaal, waar je de bieren vers van de tap proeft.',
    facts: [
      "Staat vooral bekend om hoppige bieren zoals IPA's.",
      'Je kunt er terecht in het eigen proeflokaal.',
    ],
    latitude: 52.4700,
    longitude: 4.8200,
  ),
  Brewery(
    id: 2,
    title: 'Saint Sixtus',
    distance: '1.2 km bij jou vandaan',
    rating: '4.9',
    tags: ['TRAPPIST', 'BEPERKT'],
    location: 'Westvleteren, België',
    founded: '1831',
    about:
        'De Sint-Sixtusabdij is een trappistenabdij in West-Vlaanderen.',
    facts: [
      'Het bier wordt gebrouwen door trappistenmonniken.',
      'Westvleteren 12 is wereldwijd bekend.',
    ],
    latitude: 50.9020,
    longitude: 2.7150,
  ),
  Brewery(
    id: 3,
    title: 'De Molen',
    distance: '3.5 km bij jou vandaan',
    rating: '4.7',
    tags: ['STOUTS', 'BARREL'],
    location: 'Bodegraven',
    founded: '2004',
    about:
        'Brouwerij De Molen begon in de historische korenmolen De Arkduif in Bodegraven.',
    facts: [
      'Bekend om zware stouts.',
      'Organiseert jaarlijks het bierfestival Borefts.',
    ],
    latitude: 52.0850,
    longitude: 4.7460,
  ),
  grutePierProeflokaal,

  // Groningen
  Brewery(
    id: 5,
    title: 'Baxbier',
    distance: 'Groningen',
    rating: '4.7',
    tags: ['MODERN', 'IPA'],
    location: 'Groningen',
    about: 'Een moderne brouwerij uit Groningen, bekend om frisse IPA\'s.',
    facts: ['Populair bij de nieuwe generatie craftbierliefhebbers in het noorden.'],
    latitude: 53.2250,
    longitude: 6.5700,
  ),
  Brewery(
    id: 6,
    title: 'Stadsbrouwerij Groningen',
    distance: 'Groningen',
    rating: '4.4',
    tags: ['STAD', 'BLOND'],
    location: 'Groningen',
    about: 'De stadsbrouwerij van Groningen, met een toegankelijk blond bier als vlaggenschip.',
    facts: ['Gevestigd in het hart van de stad Groningen.'],
    latitude: 53.2194,
    longitude: 6.5665,
  ),
  Brewery(
    id: 7,
    title: 'Rebelse Moed',
    distance: 'Groningen',
    rating: '4.5',
    tags: ['CRAFT', 'ORGANIC'],
    location: 'Groningen',
    about: 'Een kleine, onafhankelijke craftbrouwerij met biologische bieren.',
    facts: ['Brouwt met biologische ingrediënten.'],
    latitude: 53.2120,
    longitude: 6.5600,
  ),

  // Friesland
  Brewery(
    id: 8,
    title: 'US Heit Bier',
    distance: 'Friesland',
    rating: '4.4',
    tags: ['FRISSIAN', 'WISKY'],
    location: 'Friesland',
    about: 'Een Friese brouwerij die onder andere whisky-vat gerijpte bieren maakt.',
    facts: ['Combineert Friese trots met whisky-vatrijping.'],
    latitude: 53.0450,
    longitude: 5.6580,
  ),
  Brewery(
    id: 9,
    title: 'Brouwerij Dockum',
    distance: 'Dokkum',
    rating: '4.5',
    tags: ['LOCAL', 'CRAFT'],
    location: 'Dokkum',
    about: 'Een lokale craftbrouwerij uit het Friese Dokkum.',
    facts: ['Genoemd naar de historische stad Dokkum.'],
    latitude: 53.3262,
    longitude: 5.9995,
  ),
  Brewery(
    id: 10,
    title: 'Grutte Pier Brewery',
    distance: 'Friesland',
    rating: '4.6',
    tags: ['TRIPLE', 'BLOND'],
    location: 'Friesland',
    about: 'Een Friese brouwerij met een klassieke tripel en blond in het assortiment.',
    facts: ['Vernoemd naar dezelfde Friese volksheld als het Grutte Pier Proeflokaal.'],
    latitude: 53.1500,
    longitude: 5.4300,
  ),

  // Drenthe
  Brewery(
    id: 11,
    title: 'Maallust',
    distance: 'Drenthe',
    rating: '4.7',
    tags: ['HISTORISCH', 'MATERIAAL'],
    location: 'Drenthe',
    about: 'Een Drentse brouwerij met oog voor historische brouwmethoden.',
    facts: ['Gevestigd in Drenthe, bekend om ambachtelijke bieren.'],
    latitude: 53.0290,
    longitude: 6.3050,
  ),
  Brewery(
    id: 12,
    title: 'Brouwerij & Proeflokaal Beilen',
    distance: 'Beilen',
    rating: '4.3',
    tags: ['PROEFLOKAAL'],
    location: 'Beilen',
    about: 'Brouwerij met eigen proeflokaal in het Drentse Beilen.',
    facts: ['Je kunt er zowel brouwen bekijken als proeven.'],
    latitude: 52.8550,
    longitude: 6.5120,
  ),
  Brewery(
    id: 13,
    title: 'Salie & Zware Jongens',
    distance: 'Drenthe',
    rating: '4.4',
    tags: ['LOCAL'],
    location: 'Drenthe',
    about: 'Een lokale Drentse brouwerij met een speels karakter.',
    facts: ['Bekend om de opvallende naam en lokale bieren.'],
    latitude: 52.9800,
    longitude: 6.5600,
  ),

  // Overijssel
  Brewery(
    id: 14,
    title: 'Dolle Mina',
    distance: 'Overijssel',
    rating: '4.3',
    tags: ['LOCAL'],
    location: 'Overijssel',
    about: 'Een lokale brouwerij uit Overijssel.',
    facts: ['Vernoemd naar de bekende feministische beweging.'],
    latitude: 52.5010,
    longitude: 6.0830,
  ),
  Brewery(
    id: 15,
    title: 'Mommeriete',
    distance: 'Overijssel',
    rating: '4.5',
    tags: ['STOUT', 'BOCK'],
    location: 'Overijssel',
    about: 'Bekend om stevige stouts en bocks uit Overijssel.',
    facts: ['Specialiseert zich in zwaardere, moutige bierstijlen.'],
    latitude: 52.6100,
    longitude: 6.7150,
  ),
  Brewery(
    id: 16,
    title: 'Eanske Bier',
    distance: 'Enschede',
    rating: '4.6',
    tags: ['ENSCHEDE', 'IPA'],
    location: 'Enschede',
    about: 'Een Enschedese brouwerij met een voorliefde voor hoppige IPA\'s.',
    facts: ['De naam verwijst naar de Twentse benaming voor Enschede.'],
    latitude: 52.2215,
    longitude: 6.8937,
  ),
  Brewery(
    id: 17,
    title: 'Brouwerij Huttenkloas',
    distance: 'Twente',
    rating: '4.5',
    tags: ['TWENTE', 'CRAFT'],
    location: 'Twente',
    about: 'Een Twentse craftbrouwerij met streekeigen bieren.',
    facts: ['Gevestigd in de regio Twente.'],
    latitude: 52.3400,
    longitude: 6.8100,
  ),

  // Flevoland
  Brewery(
    id: 18,
    title: 'Stadsbrouwerij Zeewolde',
    distance: 'Zeewolde',
    rating: '4.3',
    tags: ['LOCAL'],
    location: 'Zeewolde',
    about: 'De lokale stadsbrouwerij van Zeewolde.',
    facts: ['Eén van de jongere brouwerijen van Flevoland.'],
    latitude: 52.3330,
    longitude: 5.5350,
  ),
  Brewery(
    id: 19,
    title: 'Compaan Flevoland',
    distance: 'Flevoland',
    rating: '4.4',
    tags: ['CRAFT'],
    location: 'Flevoland',
    about: 'Een craftbrouwerij uit de polder van Flevoland.',
    facts: ['Brouwt met een moderne, experimentele aanpak.'],
    latitude: 52.5120,
    longitude: 5.4710,
  ),

  // Gelderland
  Brewery(
    id: 20,
    title: 'Oersoep',
    distance: 'Gelderland',
    rating: '4.6',
    tags: ['SOUR', 'EXPERIMENTAL'],
    location: 'Gelderland',
    about: 'Bekend om experimentele zure bieren uit Gelderland.',
    facts: ['Specialist in sour- en experimentele bierstijlen.'],
    latitude: 51.8426,
    longitude: 5.8584,
  ),
  Brewery(
    id: 21,
    title: 'Gajes Bier',
    distance: 'Gelderland',
    rating: '4.4',
    tags: ['BLOND', 'TRIPLE'],
    location: 'Gelderland',
    about: 'Een Gelderse brouwerij met een blond en een tripel als vaste kern.',
    facts: ['Populair in de regio rond Apeldoorn en Zutphen.'],
    latitude: 52.2112,
    longitude: 5.9699,
  ),
  Brewery(
    id: 22,
    title: 'Bronckhorster Brewing Company',
    distance: 'Gelderland',
    rating: '4.6',
    tags: ['CRAFT', 'WOOD'],
    location: 'Gelderland',
    about: 'Bekend om houtgerijpte craftbieren uit de Achterhoek.',
    facts: ['Werkt veel met vatrijping op eikenhouten vaten.'],
    latitude: 52.0510,
    longitude: 6.2300,
  ),
  Brewery(
    id: 23,
    title: 'Stadsbrouwerij Wageningen',
    distance: 'Wageningen',
    rating: '4.4',
    tags: ['ORGANIC'],
    location: 'Wageningen',
    about: 'De stadsbrouwerij van Wageningen, met biologische bieren.',
    facts: ['Past bij het duurzame imago van de universiteitsstad.'],
    latitude: 51.9692,
    longitude: 5.6657,
  ),
  Brewery(
    id: 24,
    title: 'AXL Brewery',
    distance: 'Apeldoorn',
    rating: '4.5',
    tags: ['APELDOORN'],
    location: 'Apeldoorn',
    about: 'Een brouwerij gevestigd in Apeldoorn.',
    facts: ['Eén van de craftbrouwerijen die Apeldoorn op de bierkaart zet.'],
    latitude: 52.1326,
    longitude: 5.9140,
  ),
  Brewery(
    id: 25,
    title: 'Pantsers Bier',
    distance: 'Arnhem',
    rating: '4.3',
    tags: ['ARNHEM'],
    location: 'Arnhem',
    about: 'Een lokale brouwerij uit Arnhem.',
    facts: ['Draagt de naam van de stad Arnhem uit.'],
    latitude: 51.9850,
    longitude: 5.9100,
  ),

  // Utrecht
  Brewery(
    id: 26,
    title: 'Uiltje Brewing Company',
    distance: 'Haarlem',
    rating: '4.7',
    tags: ['IPA', 'MODERN'],
    location: 'Haarlem',
    about: 'Een populaire moderne brouwerij, bekend om zijn IPA\'s.',
    facts: ['Eén van de bekendere Nederlandse craftbrouwerijen.'],
    latitude: 52.3874,
    longitude: 4.6462,
  ),
  Brewery(
    id: 27,
    title: 'Brouwerij De Leckere',
    distance: 'Utrecht',
    rating: '4.3',
    tags: ['BIOLOGISCH', 'LOCAL'],
    location: 'Utrecht',
    about: 'Een Utrechtse brouwerij met volledig biologische bieren.',
    facts: ['Brouwt uitsluitend met biologische grondstoffen.'],
    latitude: 52.0313,
    longitude: 5.0997,
  ),
  Brewery(
    id: 28,
    title: 'Brewpub De Kromme Haring',
    distance: 'Utrecht',
    rating: '4.6',
    tags: ['WILD', 'SOUR'],
    location: 'Utrecht',
    about: 'Een Utrechtse brewpub gespecialiseerd in wilde en zure bieren.',
    facts: ['Brouwt en schenkt op dezelfde locatie.'],
    latitude: 52.0780,
    longitude: 5.1320,
  ),
  Brewery(
    id: 29,
    title: 'Brouwerij Maximus',
    distance: 'Utrecht',
    rating: '4.5',
    tags: ['TERRAS', 'DUBBEL'],
    location: 'Utrecht',
    about: 'Een Utrechtse brouwerij met een gezellig terras en een stevige dubbel.',
    facts: ['Populair vanwege het terras naast de brouwketels.'],
    latitude: 52.0910,
    longitude: 5.0350,
  ),
  Brewery(
    id: 30,
    title: 'VandeStreek Bier',
    distance: 'Utrecht',
    rating: '4.6',
    tags: ['IPA', 'ZERO'],
    location: 'Utrecht',
    about: 'Utrechtse brouwerij bekend om IPA\'s en alcoholvrije bieren.',
    facts: ['Brengt ook een 0.0%-lijn uit.'],
    latitude: 52.1100,
    longitude: 5.0700,
  ),

  // Noord-Holland
  Brewery(
    id: 31,
    title: 'Brouwerij Het IJ',
    distance: 'Amsterdam',
    rating: '4.6',
    tags: ['IPA', 'BLOND'],
    location: 'Amsterdam',
    about: 'Amsterdamse brouwerij bij een molen, bekend van de IJwit en Columbus.',
    facts: ['Gevestigd naast molen De Gooyer in Amsterdam.'],
    latitude: 52.3667,
    longitude: 4.9306,
  ),
  Brewery(
    id: 32,
    title: 'Poesiat & Kater',
    distance: 'Amsterdam',
    rating: '4.5',
    tags: ['CRAFT', 'TERRAS'],
    location: 'Amsterdam',
    about: 'Amsterdamse craftbrouwerij met een populair terras.',
    facts: ['Bekend van de brouwerij aan het water in Amsterdam-Noord.'],
    latitude: 52.3565,
    longitude: 4.9312,
  ),
  Brewery(
    id: 33,
    title: 'Brouwerij Troost',
    distance: 'Amsterdam',
    rating: '4.4',
    tags: ['BURGER', 'BIER'],
    location: 'Amsterdam',
    about: 'Amsterdamse brouwerij die bier combineert met een uitgebreide keuken.',
    facts: ['Heeft meerdere vestigingen door Amsterdam.'],
    latitude: 52.3533,
    longitude: 4.8805,
  ),
  Brewery(
    id: 34,
    title: 'Jopenkerk',
    distance: 'Haarlem',
    rating: '4.5',
    tags: ['HAARLEM', 'PROEFLOKAAL'],
    location: 'Haarlem',
    about: 'Brouwerij en proeflokaal gevestigd in een voormalige kerk in Haarlem.',
    facts: ['Brouwt in een historisch kerkgebouw in het centrum van Haarlem.'],
    latitude: 52.3810,
    longitude: 4.6362,
  ),
  Brewery(
    id: 35,
    title: 'Egmondse Bierbrouwerij',
    distance: 'Egmond',
    rating: '4.4',
    tags: ['ABDIJ', 'SAINT'],
    location: 'Egmond',
    about: 'Abdijbieren gebrouwen bij de Sint-Adelbertabdij in Egmond.',
    facts: ['Brouwt in de traditie van Nederlandse abdijbieren.'],
    latitude: 52.6170,
    longitude: 4.6300,
  ),
  Brewery(
    id: 36,
    title: 'Brouwerij Homeland',
    distance: 'Amsterdam',
    rating: '4.5',
    tags: ['AMSTERDAM', 'NAVY'],
    location: 'Amsterdam',
    about: 'Amsterdamse brouwerij op het voormalige marineterrein.',
    facts: ['Gevestigd op de historische Marineterrein-locatie.'],
    latitude: 52.3730,
    longitude: 4.9150,
  ),

  // Zuid-Holland
  Brewery(
    id: 37,
    title: 'Brouwerij Noordt',
    distance: 'Rotterdam',
    rating: '4.5',
    tags: ['IPA', 'LAGER'],
    location: 'Rotterdam',
    about: 'Rotterdamse brouwerij met een breed assortiment van IPA tot lager.',
    facts: ['Eén van de craftbrouwerijen die Rotterdam op de kaart zet.'],
    latitude: 51.9310,
    longitude: 4.4750,
  ),
  Brewery(
    id: 38,
    title: 'Kaapse Brouwers',
    distance: 'Rotterdam',
    rating: '4.6',
    tags: ['CRAFT', 'IPA'],
    location: 'Rotterdam',
    about: 'Populaire Rotterdamse craftbrouwerij op Katendrecht.',
    facts: ['Gevestigd op de voormalige Kaap van Katendrecht.'],
    latitude: 51.9073,
    longitude: 4.8566,
  ),
  Brewery(
    id: 39,
    title: 'Stadsbrouwerij De Pelgrim',
    distance: 'Rotterdam',
    rating: '4.4',
    tags: ['HISTORISCH', 'BLOND'],
    location: 'Rotterdam',
    about: 'Historische stadsbrouwerij in het centrum van Rotterdam.',
    facts: ['Vernoemd naar de Pelgrimvaders die ooit via Rotterdam vertrokken.'],
    latitude: 51.9244,
    longitude: 4.4777,
  ),
  Brewery(
    id: 40,
    title: 'Delftse Brouwers',
    distance: 'Delft',
    rating: '4.4',
    tags: ['DELFT', 'LOCAL'],
    location: 'Delft',
    about: 'Lokale brouwerij uit de studentenstad Delft.',
    facts: ['Populair onder studenten en Delftenaren.'],
    latitude: 52.0116,
    longitude: 4.3571,
  ),

  // Zeeland
  Brewery(
    id: 41,
    title: 'Emelisse',
    distance: 'Zeeland',
    rating: '4.6',
    tags: ['BLACK', 'IPA'],
    location: 'Zeeland',
    about: 'Zeeuwse brouwerij bekend om zware imperial stouts en IPA\'s.',
    facts: ['Internationaal bekend bij liefhebbers van zware bierstijlen.'],
    latitude: 51.5210,
    longitude: 3.5680,
  ),
  Brewery(
    id: 42,
    title: 'Stadsbrouwerij Middelburg',
    distance: 'Middelburg',
    rating: '4.4',
    tags: ['LOCAL'],
    location: 'Middelburg',
    about: 'De lokale stadsbrouwerij van Middelburg.',
    facts: ['Gevestigd in de Zeeuwse hoofdstad Middelburg.'],
    latitude: 51.4988,
    longitude: 3.6108,
  ),
  Brewery(
    id: 43,
    title: 'Dutch Bargain',
    distance: 'Zeeland',
    rating: '4.5',
    tags: ['BORDER', 'CRAFT'],
    location: 'Zeeland',
    about: 'Craftbrouwerij dicht bij de Belgische grens in Zeeuws-Vlaanderen.',
    facts: ['Gevestigd vlak bij de grens met België.'],
    latitude: 51.3500,
    longitude: 3.5000,
  ),

  // Noord-Brabant
  Brewery(
    id: 44,
    title: 'Brouwerij Frontaal',
    distance: 'Noord-Brabant',
    rating: '4.7',
    tags: ['IPA', 'CRAFT'],
    location: 'Noord-Brabant',
    about: 'Brabantse craftbrouwerij met een sterke reputatie voor IPA\'s.',
    facts: ['Eén van de bekendere Brabantse craftbrouwerijen.'],
    latitude: 51.5900,
    longitude: 4.7750,
  ),
  Brewery(
    id: 45,
    title: 'La Trappe (Trappistenbrouwerij)',
    distance: 'Tilburg',
    rating: '4.8',
    tags: ['TRAPPIST', 'KLASSIEK'],
    location: 'Berkel-Enschot',
    founded: '1884',
    about: 'De enige Nederlandse Trappistenbrouwerij, bij de Abdij Onze Lieve Vrouw van Koningshoeven.',
    facts: [
      'Eén van de weinige brouwerijen ter wereld met het officiële "Authentic Trappist Product"-keurmerk.',
      'De monniken van de abdij zijn nog altijd betrokken bij de brouwerij.',
    ],
    latitude: 51.5372,
    longitude: 5.0315,
  ),
  Brewery(
    id: 46,
    title: 'Stadsbrouwerij Eindhoven',
    distance: 'Eindhoven',
    rating: '4.5',
    tags: ['STAD', 'PROEFLOKAAL'],
    location: 'Eindhoven',
    about: 'De stadsbrouwerij van Eindhoven, met eigen proeflokaal.',
    facts: ['Gevestigd in het centrum van Eindhoven.'],
    latitude: 51.4416,
    longitude: 5.4697,
  ),
  Brewery(
    id: 47,
    title: 'Brouwerij 75',
    distance: 'Noord-Brabant',
    rating: '4.4',
    tags: ['CRAFT'],
    location: 'Noord-Brabant',
    about: 'Een Brabantse craftbrouwerij met een compact, kwalitatief assortiment.',
    facts: ['Kleinschalige brouwerij uit Brabant.'],
    latitude: 51.6920,
    longitude: 5.3030,
  ),
  Brewery(
    id: 48,
    title: 'Brouwerij Van Vollenhoven',
    distance: 'Noord-Brabant',
    rating: '4.3',
    tags: ['TRADITIONAL'],
    location: 'Noord-Brabant',
    about: 'Een traditionele Brabantse brouwerij met een klassiek bierassortiment.',
    facts: ['Zet in op traditionele brouwmethoden.'],
    latitude: 51.6900,
    longitude: 5.3000,
  ),
  Brewery(
    id: 49,
    title: 'Stadsbrouwerij Tilburg',
    distance: 'Tilburg',
    rating: '4.5',
    tags: ['TILBURG'],
    location: 'Tilburg',
    about: 'De stadsbrouwerij van Tilburg.',
    facts: ['Draagt de naam van de stad Tilburg uit.'],
    latitude: 51.5550,
    longitude: 5.0910,
  ),

  // Limburg
  Brewery(
    id: 50,
    title: 'Brand Bierbrouwerij',
    distance: 'Wijlre',
    rating: '4.5',
    tags: ['LIMBURG', 'PILSNER'],
    location: 'Wijlre',
    founded: '1871',
    about: 'Eén van de oudste Nederlandse brouwerijen, bekend van de Brand Pilsner.',
    facts: ['Al sinds 1871 actief in Limburg.'],
    latitude: 51.6310,
    longitude: 5.9180,
  ),
  Brewery(
    id: 51,
    title: 'Stadsbrouwerij Maastricht',
    distance: 'Maastricht',
    rating: '4.6',
    tags: ['HISTORISCH', 'PROEFLOKAAL'],
    location: 'Maastricht',
    about: 'Historische stadsbrouwerij in het centrum van Maastricht.',
    facts: ['Gevestigd in de historische binnenstad van Maastricht.'],
    latitude: 50.8483,
    longitude: 5.6889,
  ),
  Brewery(
    id: 52,
    title: 'Gulpener Bierbrouwerij',
    distance: 'Gulpen',
    rating: '4.7',
    tags: ['BIOLOGISCH', 'LOCAL'],
    location: 'Gulpen',
    founded: '1825',
    about: 'Zuid-Limburgse brouwerij die sterk inzet op lokale en biologische ingrediënten.',
    facts: ['Werkt samen met lokale boeren voor streekeigen grondstoffen.'],
    latitude: 50.8250,
    longitude: 5.8970,
  ),
  Brewery(
    id: 53,
    title: 'Lindeboom Bierbrouwerij',
    distance: 'Neer',
    rating: '4.4',
    tags: ['NEER', 'FAMILY'],
    location: 'Neer',
    founded: '1870',
    about: 'Familiebrouwerij uit het Limburgse Neer.',
    facts: ['Al meerdere generaties in familiebezit.'],
    latitude: 51.4800,
    longitude: 5.9300,
  ),
];
